          script: |
            cd ~/my_app/frontend-project
            git pull origin main
            echo "${{ secrets.ENV_FILE_FRONTEND }}" > .env
            
            # Запускаем только фронтенд
            docker compose up -d --build
